/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Olx Clone",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <body
          className=
            "h-full w-full bg-white dark:bg-slate-900 text-slate-900 dark:text-white"
        >
          <Navbar/>
          <div className="max-w-full mx-auto p-4 md:px-12">
            {children}
          </div>
          <Footer/>
        </body>
    </html>
  );
}
